#!/bin/bash
set -e

SCRIPT_NAME="xbps-updater"
INSTALL_DIR="/usr/local/bin"

echo -e "\e[1mСкачивание $SCRIPT_NAME...\e[0m"
mkdir -p "/tmp/$SCRIPT_NAME"
curl -fsSL \
"https://raw.githubusercontent.com/idoffront/xbps-updater/main/update" -o "/tmp/$SCRIPT_NAME/update"
echo
echo -e "\e[1mУстановка в $INSTALL_DIR\e[0m"
sudo install -m 755 "/tmp/$SCRIPT_NAME/update" "$INSTALL_DIR/update"
echo
echo -e "\e[1mУдаление временных файлов\e[0m"
rm -rf "/tmp/$SCRIPT_NAME"
echo
echo -e "\e[1mУстановка успешно завершена! Запустите: update\e[0m"
exit
