#!/bin/bash

source /etc/os-release

case "$ID" in
    void)
        curl -fsSL https://raw.githubusercontent.com/idoffront/void-helper/main/void/install | bash
        ;;
    ubuntu|debian|linuxmint)
        curl -fsSL https://raw.githubusercontent.com/idoffront/void-helper/main/debian/install | bash
        ;;
    fedora)
        curl -fsSL https://raw.githubusercontent.com/idoffront/void-helper/main/fedora/install | bash
        ;;
    *)
        echo -e "\e[1mДистрибутив не поддерживается.\e[0m"
        echo
        echo "Создайте issue на ГитХабе проекта и возможно появится поддержка вашего дистрибутива."
        exit
esac
