#!/bin/bash

info() {
    echo -e "\e[1mИнформация о Системе\e[0m"
    echo "--------------------"

    distro=$(grep '^NAME=' /etc/os-release | cut -d= -f2 | tr -d '""')

    kernel=$(uname -r)

#    packages=$(dnf list | wc -l)

    de=${XDG_CURRENT_DESKTOP:-Unknown}

    disk=$(df -h / | awk 'NR==2 {print $1 " " $2 " / " $3}')

    uptime=$(uptime -p)

    printf "Дистрибутив  : %s\n" "$distro"
    printf "Ядро         : %s\n" "$kernel"
#    printf "Пакеты       : %s\n" "$packages"
    printf "Граф. Окруж. : %s\n" "$de"
    printf "Диск         : %s\n" "$disk"
    printf "Время работы : %s\n" "$uptime"
#    echo
#    echo "Репозитории:"

#    xbps-query -L | sed 's/^/ [*] /'
}

update() {
    sudo -v
    echo -e "\e[1mСинхронизация репозитриев и Обновление пакетов\e[0m"
    echo
    sudo dnf upgrade
    echo
    echo -e "\e[1mПакеты обновлены или обновлений нет\e[0m"
    echo
    sudo dnf autoremove
    echo
    echo -e "\e[1mГотово!\e[0m"
}

check_service() {
    service=$1

    status=$(systemctl is-active "$service" )

    if echo "$status" |grep -q '^active'; then
        echo "[ОК] $service"
    else
        echo "[НЕ РАБОТАЕТ] $service"
    fi
}

check() {
    sudo -v
    echo -e "\e[1mПроверка служб\e[0m"
    echo "-------------"
    echo -e "\e[1mСеть:\e[0m"
    check_service "NetworkManager"
    check_service "wpa_supplicant"
    echo -e "\e[1mЗвук:\e[0m"
    any_diff_process_BLYAT "pipewire"
    any_diff_process_BLYAT "wireplumber"
    echo -e "\e[1mОстальное:\e[0m"
    check_service "dbus"
    check_service "polkit"
    check_service "bluetoothd"
    check_service "sshd"
    echo
    echo "NetworkManager и wpa_supplicant взаимозаменяемые, если один работает, а другой нет - всё хорошо."
    echo "Почему у вас может не работать bluetoothd, думаю, вы сами знаете."
}

any_diff_process_BLYAT() {
    process="$1"

    if pgrep "$process" >/dev/null; then
        echo "[ОК] $process"
    else
        echo "[НЕ РАБОТАЕТ] $process"
    fi
}

update-vh() {
    echo -e "\e[1mОбновление Void-Helper\e[0m"
    curl -fsSL https://raw.githubusercontent.com/idoffront/void-helper/main/Void/install | bash
    echo -e "\e[1mОбновление завершено.\e[0m"
}

find() {
    packet=$1
    query=$(dnf search "$packet" 2>/dev/null)
    
    echo -e "\e[1mПоиск пакета:\e[0m"
    if echo "$query" | grep -q  'Matched'; then
        dnf search "$packet"
    else
        echo -e "\e[1mПакет не найден.\e[0m"
        echo -e "\e[1mПопробуйте написать название с большой, либо маленькой буквы.\e[0m"
    fi
}

case "$1" in
    info)
        info
        ;;

    update)
        update
        ;;

    check_s)
        check_service "$2"
        ;;

    check)
        check
        ;;
        
    update-vh)
        update-vh
        ;;
        
    find)
        find "$2"
        ;;
        
    *)
        echo "Доступные команды: vh {info|find|update|update-vh|check|check_s}"
        echo -e "\e[1m~~~\e[0m"
        echo "info - выдает достаточно useful информацию об системе"
        echo "find - находит пакет в репозиториях"
        echo "update - обновляет систему/пакеты"
        echo "update-vh - обновляет этот скрипт"
        echo "check - проверяет важные сервисы"
        echo "check_s [сервис] - проверяет нужный вам сервис"
        ;;


esac
